import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#111b15', paddingTop: 24 },
  brand: { color: '#d5f5df', fontSize: 30, fontWeight: '700', paddingHorizontal: 16 },
  tagline: { color: '#8fb39a', paddingHorizontal: 16, marginBottom: 12 },
  tabs: { flexDirection: 'row', gap: 8, paddingHorizontal: 16, marginBottom: 10 },
  tabButton: {
    borderWidth: 1,
    borderColor: '#2d4738',
    borderRadius: 18,
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#16251d',
  },
  tabButtonActive: { backgroundColor: '#2c5e43', borderColor: '#4b8a68' },
  tabButtonText: { color: '#d5f5df', textTransform: 'capitalize', fontWeight: '600' },
  content: { padding: 16, gap: 12, paddingBottom: 30 },
  card: {
    borderWidth: 1,
    borderColor: '#2b4336',
    borderRadius: 14,
    padding: 12,
    backgroundColor: '#16251d',
    gap: 8,
  },
  cardTitle: { color: '#d5f5df', fontSize: 18, fontWeight: '700', textTransform: 'capitalize' },
  meta: { color: '#aac6b3' },
  input: {
    borderWidth: 1,
    borderColor: '#385945',
    borderRadius: 10,
    color: '#e3fff0',
    padding: 10,
    backgroundColor: '#102017',
  },
  primaryButton: {
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: '#3d8f62',
    alignItems: 'center',
  },
  secondaryButton: {
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: '#305643',
    alignItems: 'center',
    flex: 1,
  },
  buttonText: { color: '#effff6', fontWeight: '600' },
  chipsRow: { marginVertical: 4 },
  chip: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#335442',
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginRight: 8,
    backgroundColor: '#18281f',
  },
  chipActive: { backgroundColor: '#2f6f4e' },
  chipText: { color: '#d5f5df' },
  inlineRow: { flexDirection: 'row', gap: 8 },
  preview: { width: '100%', height: 180, borderRadius: 10 },
  plantCard: {
    borderWidth: 1,
    borderColor: '#2b4336',
    borderRadius: 14,
    backgroundColor: '#16251d',
    padding: 10,
    flexDirection: 'row',
    gap: 10,
  },
  plantImage: { width: 100, height: 100, borderRadius: 10 },
  plantInfo: { flex: 1, gap: 3 },
  plantName: { color: '#effff6', fontSize: 18, fontWeight: '700' },
  smallButton: { flex: 1, borderRadius: 8, paddingVertical: 8, backgroundColor: '#2f6f4e', alignItems: 'center' },
  tinyButton: { borderWidth: 1, borderColor: '#3d634f', borderRadius: 8, paddingVertical: 4, paddingHorizontal: 8 },
  tinyButtonText: { color: '#b8d6c2', fontSize: 12 },
});
